version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: php-di/php-di
    versions:
    - 6.3.0
    - 6.3.1
  - dependency-name: symfony/polyfill-ctype
    versions:
    - 1.22.0
  - dependency-name: symfony/polyfill-util
    versions:
    - 1.22.0
  - dependency-name: phpspec/prophecy
    versions:
    - 1.12.2
